### ISSUE TITLE
What about openswoole?

### ISSUE THREAD

**Issue by kingIZZZY** [hyperf/database-pgsql#1]
1. Any particular reason `ext-swoole` is being used rather than `ext-openswoole` ?
2. Is it possible somehow to support both/either?
3. Doesn't `ext-openswoole` have some good features for PDO connection pooling which can be used for postgresql? Or are there any clear advantages/disadvantages of swoole/openswoole in regards to non-blocking concurrency with postgres?

**Comment by huangzhhui** [comment]
Sorry, at present, Hyperf does not support OpenSwoole, and there is no such plan for the time being. In fact, I don't think OpenSwoole is a sustainable development project.

**Comment by kingIZZZY** [comment]
Understood - thanks
