### ISSUE TITLE
v3.0.0-rc.1 inconsistent type strictness - PHP Fatal error: PostgresGrammar::$transactions must not be defined

### ISSUE THREAD

**Issue by kingIZZZY** [hyperf/database-pgsql#2]
[src/Schema/Grammars/PostgresGrammar.php:24](https://github.com/hyperf/database-pgsql/blob/master/src/Schema/Grammars/PostgresGrammar.php#L24)
```php
    /**
     * If this Grammars supports schema changes wrapped in a transaction.
     */
    protected bool $transactions = true;
```
```
PHP Fatal error:
Type of Hyperf\Database\PgSQL\Schema\Grammars\PostgresGrammar::$transactions must not be defined
(as in class Hyperf\Database\Schema\Grammars\Grammar)
in /app/vendor/hyperf/database-pgsql/src/Schema/Grammars/PostgresGrammar.php on line 19
```

Either should be fixed to

```diff
-protected bool $transactions = true;
+protected $transactions = true;
```

Or in the [hyperf/database](https://github.com/hyperf/database/blob/v3.0.0-rc.1/src/Schema/Grammars/Grammar.php#L29) project [src/Schema/Grammars/Grammar.php:L29](https://github.com/hyperf/database/blob/v3.0.0-rc.1/src/Schema/Grammars/Grammar.php#L29) Should be fixed to

```diff
-protected $transactions = false;
+protected bool $transactions = false;
```

See https://github.com/hyperf/database/issues/16

**Comment by kingIZZZY** [comment]
Sorry looks like this was applicable to v3.0.0-rc.1 and fixed in master

**Comment by limingxinleo** [comment]
Yes.
